/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./resources/js/components/AppFooter.vue')['default']
    AppHead: typeof import('./resources/js/components/AppHead.vue')['default']
    ArticlesCard: typeof import('./resources/js/components/Articles/Card.vue')['default']
    ArticlesFeatured: typeof import('./resources/js/components/Articles/Featured.vue')['default']
    ArticlesFeaturedSection: typeof import('./resources/js/components/Articles/FeaturedSection.vue')['default']
    IconsFacebook: typeof import('./resources/js/components/Icons/Facebook.vue')['default']
    IconsInstagram: typeof import('./resources/js/components/Icons/Instagram.vue')['default']
    IconsTiktok: typeof import('./resources/js/components/Icons/Tiktok.vue')['default']
    IconsTwitch: typeof import('./resources/js/components/Icons/Twitch.vue')['default']
    IconsX: typeof import('./resources/js/components/Icons/X.vue')['default']
    IconsYoutube: typeof import('./resources/js/components/Icons/Youtube.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
    LiveStream: typeof import('./resources/js/components/LiveStream.vue')['default']
    NavBar: typeof import('./resources/js/components/NavBar.vue')['default']
    Pagination: typeof import('./resources/js/components/Pagination.vue')['default']
    Search: typeof import('./resources/js/components/Search.vue')['default']
    ThemeToggle: typeof import('./resources/js/components/ThemeToggle.vue')['default']
  }
}
