/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHead: typeof import('./../components/AppHead.vue')['default']
    ArticlesCard: typeof import('./../components/Articles/Card.vue')['default']
    ArticlesFeatured: typeof import('./../components/Articles/Featured.vue')['default']
    ArticlesFeaturedSection: typeof import('./../components/Articles/FeaturedSection.vue')['default']
    IconsFacebook: typeof import('./../components/Icons/Facebook.vue')['default']
    IconsIconLoading: typeof import('./../components/Icons/IconLoading.vue')['default']
    IconsInstagram: typeof import('./../components/Icons/Instagram.vue')['default']
    IconsTiktok: typeof import('./../components/Icons/Tiktok.vue')['default']
    IconsTwitch: typeof import('./../components/Icons/Twitch.vue')['default']
    IconsX: typeof import('./../components/Icons/X.vue')['default']
    IconsYoutube: typeof import('./../components/Icons/Youtube.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
    LiveStream: typeof import('./../components/LiveStream.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    Search: typeof import('./../components/Search.vue')['default']
    Socials: typeof import('./../components/Socials.vue')['default']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
  }
}
